version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: osm-postgres
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: renderer
      POSTGRES_PASSWORD: renderer
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - osm-network
    restart: unless-stopped
    shm_size: 1g
    command: |
      postgres -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=512MB
      -c effective_cache_size=2GB
      -c maintenance_work_mem=256MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  tile-server:
    image: overv/openstreetmap-tile-server:2.0.1
    container_name: osm-tile-server
    command: run
    environment:
      THREADS: 4
      OSM2PGSQL_EXTRA_ARGS: "-C 2048"
      MAX_ZOOM: 18
      MIN_ZOOM: 0
      UPDATES: disabled
      PGPASSWORD: renderer
    volumes:
      - osm_tiles:/data/tiles/
      - ./osm-data/arizona-latest.osm.pbf:/data/region.osm.pbf:ro
    ports:
      - "8080:80"
    networks:
      - osm-network
    depends_on:
      - postgres
    restart: "no"
    shm_size: 2g

volumes:
  postgres_data:
  osm_tiles:

networks:
  osm-network:
    driver: bridge